[package]
name = "launchpad_ji"
version = "0.1.0"
edition = "2021"
authors = ["Fraccy"]
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug", package = "nih_plug", features = ["assert_process_allocs"] }
vst3-sys = { git = "https://github.com/robbert-vdh/vst3-sys.git", branch = "fix/drop-box-from-raw", optional = true }

[features]
default = ["vst3"]
vst3 = ["dep:vst3-sys"]

[workspace]
members = ["xtask"]